export const IS_AUTHENTICATED = 'IS_AUTHENTICATED'
export const REQUEST_PRODUCTS_LIST_FROM_SPRING = 'REQUEST_PRODUCTS_LIST_FROM_SPRING'
export const REQUEST_PRODUCT_FROM_SPRING = 'REQUEST_PRODUCT_FROM_SPRING'
export const REQUEST_FILTERED_PRODUCT_FROM_SPRING = 'REQUEST_FILTERED_PRODUCT_FROM_SPRING'
