export default {
  isAuthenticated: false,
  hideHeader: false,
  products: [],
  product: {},
  resMyRequest: "",
  resMember: {},
  cartList: [],
  orderList: [],
  reviews: [],
  review: {},
  resMemberProfile: {},
  foundrys: [],
  selectedFoundry: {},
  reservationInfo: {},
  questionBoard: {},
  questionBoards: [],
  questionComment: {},
  questionComments: [],
  orderedList:{},
  paymentList:{},
  myReservationList: [],
};